variable "region" {}
variable "gcp_project" {}
variable "credentials" {}
variable "vpc-name" {}
variable "subnet-name" {}
variable "range_name" {}
variable "ip_cidr_range" {}
variable "zone" {}
variable "machine_type" {}
variable "image" {}
variable "network" {}
variable "instance_name" {}
variable "firewall-name" {}
